### ISSUE TITLE
Error at make step

### ISSUE THREAD

**Issue by mayankamedhe** [tum-vision/fastfusion#26]
Hi,
I am getting the following error while running make-
....
[ 84%] Generating moc_onlinefusionviewer.cxx
Scanning dependencies of target onlinefusion
[ 88%] Building CXX object src/CMakeFiles/onlinefusion.dir/onlinefusionviewer_main.cpp.o
In file included from /usr/local/include/QGLViewer/vec.h:32:0,
                 from /usr/local/include/QGLViewer/quaternion.h:26,
                 from /usr/local/include/QGLViewer/keyFrameInterpolator.h:29,
                 from /usr/local/include/QGLViewer/camera.h:27,
                 from /usr/local/include/QGLViewer/qglviewer.h:26,
                 from /home/initial/fastfusion/src/onlinefusionviewer.hpp:11,
                 from /home/initial/fastfusion/src/onlinefusionviewer_main.cpp:29:
/usr/local/include/QGLViewer/config.h:43:34: error: too many decimal points in number
         : Use a version prior to 2.7.0 to remove this constraint
                                  ^
/usr/local/include/QGLViewer/config.h:80:25: fatal error: QOpenGLWidget: No such file or directory
compilation terminated.
src/CMakeFiles/onlinefusion.dir/build.make:67: recipe for target 'src/CMakeFiles/onlinefusion.dir/onlinefusionviewer_main.cpp.o' failed
make[2]: *** [src/CMakeFiles/onlinefusion.dir/onlinefusionviewer_main.cpp.o] Error 1
CMakeFiles/Makefile2:128: recipe for target 'src/CMakeFiles/onlinefusion.dir/all' failed
make[1]: *** [src/CMakeFiles/onlinefusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Does anyone know how to resolve it?
Thanks in advance

**Comment by LandauR** [comment]
I just change the QOpenGLWidget into QGLWidget and passed. This link shows the answer.
https://askubuntu.com/questions/934836/fatal-error-qtwidgets-qopenglwidget-no-such-file-or-directory
But after that more errors occurred. Plenty of grammar problems of c++

**Comment by remmel** [comment]
Try to install and use prior version, such as http://www.libqglviewer.com/src/libQGLViewer-2.6.3.tar.gz

**Comment by remmel** [comment]
Also that README.md is better https://github.com/greatwallet/fastfusion 
I made it works with Ubuntu 20.04
